### PR TITLE
Support gradle

### PR DESCRIPTION
**Pull request by IHNEL**

### CODE REVIEW

**Review by mayank19882001 — APPROVED** [review]

**Comment by danielsz** [comment]
Why are icons being committed?

**Comment by IHNEL** [comment]
@danielsz Yeah, This's my mistake while configured the ignored files.

**Comment by danielsz** [comment]
No problem, thank you for the PR, but there seems to be more changes committed that are not strictly necessary and that have more to do with your IDE and things like that. 
I also would rather have the source code as is. If you can restrict your PR to 1 gradle build script, that would be OK too.

**Comment by IHNEL** [comment]
As I wrote in Readme file: 

> What I have done: Create an empty Android Library project, then copy the source code from original repository and config to make it can be build using gradle


Since I created new project and copy the source files to, they need to be included to the commit.

**Comment by danielsz** [comment]
In its current form, the source code can be used by people who use Android Studio, as well by those who don't. This PR makes the assumption that Android Studio is present or required. But it's neither.

**Pull request closed without merging**
